# Generated by Django 3.2.19 on 2023-06-17 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=100)),
                ('author_email', models.CharField(blank=True, default='', max_length=100)),
                ('author_url', models.CharField(blank=True, default='', max_length=200)),
                ('author_ip', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_gmt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('history', models.TextField(blank=True, default='')),
                ('searchitems', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(default=False, max_length=20)),
                ('searchpages', models.TextField(blank=True, default='')),
                ('webrelatedsearch', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('morepic', models.TextField(blank=True, default='')),
                ('morevid', models.TextField(blank=True, default='')),
            ],
        ),
    ]
